services:

  mongodb:
    image: mongo:7
    container_name: mongodb
    restart: unless-stopped

    ports:
      - "27017:27017"

    volumes:
      - mongodb_data:/data/db

    networks:
      - order-network

  order-service:
    build:
      context: .
      dockerfile: order-service/Dockerfile

    container_name: order-service

    env_file:
      - .env

    ports:
      - "3000:3000"

    depends_on:
      - mongodb

    networks:
      - order-network

  payment-service:
    build:
      context: .
      dockerfile: payment-service/Dockerfile

    container_name: payment-service

    env_file:
      - .env

    depends_on:
      - mongodb

    networks:
      - order-network

  inventory-service:
    build:
      context: .
      dockerfile: inventory-service/Dockerfile

    container_name: inventory-service

    env_file:
      - .env

    depends_on:
      - mongodb

    networks:
      - order-network

  shipping-service:
    build:
      context: .
      dockerfile: shipping-service/Dockerfile

    container_name: shipping-service

    env_file:
      - .env

    depends_on:
      - mongodb

    networks:
      - order-network

  notification-service:
    build:
      context: .
      dockerfile: notification-service/Dockerfile

    container_name: notification-service

    env_file:
      - .env

    networks:
      - order-network

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile

    container_name: frontend

    ports:
      - "5173:5173"

    depends_on:
      - order-service

    networks:
      - order-network

networks:
  order-network:

volumes:
  mongodb_data:
