apiVersion: v1
kind: Secret
metadata:
  name: solace-secret
  namespace: order-processing

type: Opaque

stringData:
  SOLACE_USERNAME: solace-cloud-client
  SOLACE_PASSWORD: cf8ovgdgq3usd6ae8j0hae1jta
